spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  liquibase:
    change-log: db/master.xml
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect